version: '3.6'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0.20-alpine
    container_name: redis
    restart: always

  backend:
    build:
      context: ./
    container_name: backend
    restart: "no"
    ports:
      - "6061:6061"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY: 'tg7703_ddewirye6t0d^mam7-=42&!k&wv5dhi$$(35kouzi3ks'
